config/routes.rb
VigetLiterallySpotsYou::Application.routes.draw do
  resources :updates, :only => [:new, :create, :index, :show]
  root 'updates#latest'

  get 'twilio/process_sms' => 'twilio#process_sms'
end

app/models/alert.rb
class Alert < ActiveRecord::Base

  validates :status, :number, :presence => true
  validates :status, :inclusion => { :in => ["open", "closed"] }

  scope :open, -> { where(:status => "open") }

  def self.send_notifications
    texter = Texter.new

    open.each do |alert|
      texter.send_to(alert.number, "The parking spot just freed up!")
      alert.update_attribute(:status, "closed")
    end
  end

end

app/models/texter.rb
class Texter

  def send_to(number, message)
    client.account.messages.create({
      :from => "+14693384438",
      :to   => number,
      :body => message
    })
  end

  private

  def client
    @client ||= Twilio::REST::Client.new(ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"])
  end

end

app/models/update.rb
class Update < ActiveRecord::Base
  has_attached_file :image,       :styles => { :medium => "500x350>" }, :default_url => "http://weknowgifs.com/wp-content/uploads/2013/05/what-no-gif.gif"
  has_attached_file :canny_image, :styles => { :medium => "500x350>" }, :default_url => "http://weknowgifs.com/wp-content/uploads/2013/05/what-no-gif.gif"

  validates :status, :presence => true
  validates :status, :inclusion => { :in => ["taken", "available"] }

  def taken?
    status == "taken"
  end

  def available?
    status == "available"
  end

  def notify_if_necessary
    if available? && previous_update.taken?
      Alert.send_notifications
    end
  end

  private

  def previous_update
    Update.find(id - 1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

  def process_sms
    @update = Update.last

    if params[:Body].downcase.include?("alert") && @update.taken?
      Alert.create(:status => "open", :number => params["From"])
      render :nothing => true
    else
      render 'process_sms.xml.erb', :content_type => 'text/xml'
    end
  end

end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def latest
    @update = Update.last
  end

  def index
    @updates = Update.order("created_at DESC")
  end

  def show
    @update = Update.find(params[:id])
  end

  def new
    @update = Update.new
  end

  def create
    @update = Update.new(update_params)

    if @update.save
      @update.notify_if_necessary
      redirect_to root_url
    end
  end

  private

  def update_params
    params.require(:update).permit([:status, :image, :pixel_count, :canny_image])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>The spot is ... <%= @update.status.upcase %></div>

<br>

<div><%= image_tag(@update.image(:medium)) %></div>

<br>

<% if @update.pixel_count %>
  <div>Current pixel count is: <%= @update.pixel_count %></div>
<% end %>

<br>

<% if @update.canny_image %>
  <div><%= image_tag(@update.canny_image(:medium)) %></div>
<% end %>

<br>

<div>Created at: <%= @update.created_at.in_time_zone("MST").strftime("%X") %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VigetLiterallySpotsYou</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twilio/process_sms.xml.erb
<Response>
  <Sms>The spot is ... <%= @update.status.upcase %></Sms>
</Response>

app/views/updates/_update.html.erb
<div>The spot is ... <%= update.status.upcase %></div>

<br>

<div><%= image_tag(update.image(:medium)) %></div>

<br>

<% if update.pixel_count %>
  <div>Current pixel count is: <%= update.pixel_count %></div>
<% end %>

<br>

<% if update.canny_image %>
  <div><%= image_tag(update.canny_image(:medium)) %></div>
<% end %>

<br>

<div>Created at: <%= update.created_at.in_time_zone("MST").strftime("%x %X") %></div>

<%= link_to "All Updates", updates_path %>

app/views/updates/index.html.erb
<h3>All Updates</h3>

<ul>
  <% @updates.each do |update| %>
    <li><%= link_to update.created_at.in_time_zone("MST").strftime("%x %X"), update %></li>
    Pixel Count: <%= update.pixel_count %>
    Status: <%= update.status.upcase %>
    <br><br>
  <% end %>
</ul>

app/views/updates/latest.html.erb
<%= render "update", :update => @update %>

app/views/updates/new.html.erb
<h2>Set your status</h2>

<%= form_for @update do |f| %>
  <%= f.select :status, options_for_select(["taken", "available"]) %>
  <%= f.input :pixel_count %>
  <%= f.file_field :image %>
  <%= f.file_field :canny_image %>

  <%= f.submit %>
<% end %>

app/views/updates/show.html.erb
<%= render "update", :update => @update %>